#ifndef _SAVEMEDIATYPES_H_INCLUDED_
#define _SAVEMEDIATYPES_H_INCLUDED_
//////////////////////////////////////////////////////////////////////
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_FLAG_ENABLED			0x00000001
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_FLAG_FORCE_STEREO		0x00000002
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_FLAG_FORCE_STEREO_MIX	0x00000004
#define SAVEMEDIAPARAM_AUDIO_CAPTURE_FLAG_MIX				0x00000008
#define SAVEMEDIAPARAM_AUDIO_CAPTURE_FLAG_PTT				0x00000010
//////////////////////////////////////////////////////////////////////
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_SOURCE_TYPE_SHIFT		16
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_SOURCE_TYPE_MASK		0x00FF0000
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_SOURCE_SHIFT			24
#define	SAVEMEDIAPARAM_AUDIO_CAPTURE_SOURCE_MASK			0xFF000000
//////////////////////////////////////////////////////////////////////
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_GAMMA_CORRECT	0x00000001
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_CROP_TO_ALIGN	0x00000002
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_PRERECORD		0x00000004
#define SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_PRERECORD_TO_RAM 0x00000008
#define SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_ENCODER_SERVER	0x00000010
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_AUTO_START		0x00000020
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_AUTO_STOP		0x00000040
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_LIMIT_MASK		0x0000FF00
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_LIMIT_SHIFT		8
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_PRERECORD_SAVE	0x00010000
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_COPY_REQUIRED	0x00020000
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_FORCE_DESKTOP	0x00040000
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_FORCE_PROCESS	0x00080000
#define	SAVEMEDIAPARAM_VIDEO_CAPTURE_FLAGEX_NOT_KEYFRAME	0x80000000
//////////////////////////////////////////////////////////////////////
#endif
//////////////////////////////////////////////////////////////////////
